#
# Copyright (c) 2019-2021 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# File: .github/workflows/update-checker.yml
# Description: Source code update checker
#

name: Update Checker

env:
  REPO1_URL: https://github.com/JiaY-shi/openwrt.git
  REPO1_BRANCH: ipq60xx-devel_nss
  REPO2_URL: https://github.com/immortalwrt/immortalwrt
  REPO2_BRANCH: openwrt-23.05

on:
  workflow_dispatch:
  schedule:
   - cron: 0 16 * * *

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    # Repository 1 Steps
    - name: Get Commit Hash Repo 1
      id: getHashRepo1
      run: |
        git clone --depth 1 ${{ env.REPO1_URL }} -b ${{ env.REPO1_BRANCH }}
        echo "::set-output name=commitHash::$(git rev-parse HEAD)"

    - name: Compare Commit Hash Repo 1
      id: cacheHashRepo1
      uses: actions/cache@v2
      with:
        path: .commitHashRepo1
        key: HEAD-${{ steps.getHashRepo1.outputs.commitHash }}

    - name: Save New Commit Hash Repo 1
      if: steps.cacheHashRepo1.outputs.cache-hit != 'true'
      run: |
        echo ${{ steps.getHashRepo1.outputs.commitHash }} | tee .commitHashRepo1

    - name: Trigger build Repo 1
      if: steps.cacheHashRepo1.outputs.cache-hit != 'true'
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
        event-type: Source Code Update Repo 1

    # Repository 2 Steps
    - name: Get Commit Hash Repo 2
      id: getHashRepo2
      run: |
        git clone --depth 1 ${{ env.REPO2_URL }} -b ${{ env.REPO2_BRANCH }} .
        echo "::set-output name=commitHash::$(git rev-parse HEAD)"

    - name: Compare Commit Hash Repo 2
      id: cacheHashRepo2
      uses: actions/cache@v2
      with:
        path: .commitHashRepo2
        key: HEAD-${{ steps.getHashRepo2.outputs.commitHash }}

    - name: Save New Commit Hash Repo 2
      if: steps.cacheHashRepo2.outputs.cache-hit != 'true'
      run: |
        echo ${{ steps.getHashRepo2.outputs.commitHash }} | tee .commitHashRepo2

    - name: Trigger build Repo 2
      if: steps.cacheHashRepo2.outputs.cache-hit != 'true'
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
        event-type: Source Code Update Repo 2

    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 3
        keep_minimum_runs: 3
